### ISSUE TITLE
saveImageFileInExtStorage is true; nothing with running the methods of saveImage;

### ISSUE THREAD

**Issue by zSergeant** [RepairShopr/react-native-signature-capture#168]
saveImageFileInExtStorage is true; nothing with running the methods of saveImage;in android studio,error:
W/System.err: java.io.FileNotFoundException: /storage/emulated/0/saved_signature/signature.png (Permission denied)
W/System.err:     at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:308)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
        at com.rssignaturecapture.RSSignatureCaptureMainView.saveImage(RSSignatureCaptureMainView.java:162)
        at com.rssignaturecapture.RSSignatureCaptureViewManager.receiveCommand(RSSignatureCaptureViewManager.java:99)
        at com.rssignaturecapture.RSSignatureCaptureViewManager.receiveCommand(RSSignatureCaptureViewManager.java:18)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(NativeViewHierarchyManager.java:761)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.execute(UIViewOperationQueue.java:309)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:917)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1025)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:46)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1085)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)
W/System.err:     at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090)
        at android.view.Choreographer.doCallbacks(Choreographer.java:893)
W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:809)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
    
    in RSSignatureCaptureMainView.java:
     Log.d("React Signature", "Save file-======:" + saveFileInExtStorage);
      // save the signature
      if (saveFileInExtStorage) {
        FileOutputStream out = new FileOutputStream(file);
        this.signatureView.getSignature().compress(Bitmap.CompressFormat.PNG, 90, out);
        out.flush();
        out.close();
      } 
    I don`t know what happen

**Comment by zSergeant** [comment]
android version 9.0.1

**Comment by sostenesg7** [comment]
I had the same problem on android 9.
I solve it by changing the line **140** of **/node_modules/react-native-signature-capture/android/src/main/java/com/rssignaturecapture/RSSignatureCaptureMainView.java**

`
final void saveImage() {

      String root = getContext().getCacheDir().toString(); //--<<Change this
...
`
As i need save the signature temporarily i'm saving on cache dir, you can choose your specific directory like your application data directory.

Look at: https://developer.android.com/training/data-storage/files   for more dirs;

**Comment by NeliHarbuzava** [comment]
Have this too.
