### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'int android.app.Activity.getRequestedOrientation()' on a null object reference

### ISSUE THREAD

**Issue by jreason** [RepairShopr/react-native-signature-capture#262]
Hi,

We have been getting the following error for a while now, sometimes into the hundreads per day.
It only appears to be affecting Android devices with a wide range of difference android versions and devices.
After doing some research, i thought it might be related to the Android View State which is mentioned here:
https://github.com/software-mansion/react-native-screens#android

However, after making this change, the problem still persists.
Any ideas?

> java.lang.NullPointerException: Attempt to invoke virtual method 'int android.app.Activity.getRequestedOrientation()' on a null object reference
    at com.rssignaturecapture.RSSignatureCaptureMainView.<init>(RSSignatureCaptureMainView.java:47)
    at com.rssignaturecapture.RSSignatureCaptureViewManager.createViewInstance(RSSignatureCaptureViewManager.java:120)
    at com.rssignaturecapture.RSSignatureCaptureViewManager.createViewInstance(RSSignatureCaptureViewManager.java:19)
    at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
    at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:76)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
    at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081)
    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
    at android.view.Choreographer.doCallbacks(Choreographer.java:580)
    at android.view.Choreographer.doFrame(Choreographer.java:549)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5910)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by jedt** [comment]
@jreason can you make a test project please so I can check?

**Comment by jreason** [comment]
@jedt i have not been able to reproduce this at all in any testing environment, but my sentry logs are displaying it all the time

<img width="1191" alt="Screenshot 2022-10-13 at 12 26 54" src="https://user-images.githubusercontent.com/11260182/195584633-826b4049-14cc-43f3-8aa0-9b752a15e43f.png">

**Comment by ljmzbigsmart** [comment]
Hey guys, any ideas on how to stop this problem? Just started happening to me in my last update, but users aren´t reporting anything.
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'int android.app.Activity.getRequestedOrientation()' on a null object reference
  at com.rssignaturecapture.RSSignatureCaptureMainView.<init> (RSSignatureCaptureMainView.java:47)
  at com.rssignaturecapture.RSSignatureCaptureViewManager.createViewInstance (RSSignatureCaptureViewManager.java:120)
  at com.rssignaturecapture.RSSignatureCaptureViewManager.createViewInstance (RSSignatureCaptureViewManager.java:19)
  at com.facebook.react.uimanager.ViewManager.createViewInstance (ViewManager.java:176)
  at com.facebook.react.uimanager.ViewManager.createView (ViewManager.java:108)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.createView (NativeViewHierarchyManager.java:281)
  at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute (UIViewOperationQueue.java:160)
  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations (UIViewOperationQueue.java:1107)
  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:1078)
  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
  at com.facebook.react.modules.core.ReactChoreographer$1.doFrame (ReactChoreographer.java:89)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1542)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1553)
  at android.view.Choreographer.doCallbacks (Choreographer.java:1109)
  at android.view.Choreographer.doFrame (Choreographer.java:984)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1527)
  at android.os.Handler.handleCallback (Handler.java:958)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:257)
  at android.os.Looper.loop (Looper.java:368)
  at android.app.ActivityThread.main (ActivityThread.java:8839)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:572)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1049)
```
