### ISSUE TITLE
Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by Harshit1704** [RepairShopr/react-native-signature-capture#295]
I am using this react-native-signature-capture library, and when i start the app using the following command : 
npx react-native run-android
The metro server breaks throwing the following error, also the debugger is not working after using this library.

Error: EPERM: operation not permitted, lstat 'D:\\..\\..\\..\\..\\node_modules\react-native-signature-capture\android\build\intermediates\incremental\debug\packageDebugResources\compile-file-map.properties'
Emitted 'error' event on NodeWatcher instance at:
    at D:\\..\\..\\..\\..\\node_modules\metro-file-map\src\watchers\NodeWatcher.js:278:14
    at callback (D:\\..\\..\\..\\..\\node_modules\graceful-fs\polyfills.js:306:20)
    at FSReqCallback.oncomplete (node:fs:207:21) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'lstat',
  path: 'D:\\..\\..\\..\\..node_modules\\react-native-signature-capture\\android\\build\\intermediates\\incremental\\debug\\packageDebugResources\\compile-file-map.properties'
}

**Comment by rustyonrampage** [comment]
Same issue.
